name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change to main if that is your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject Firebase Secrets
        run: |
          sed -i 's|FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g' js/firebase-config.js
          sed -i 's|FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' js/firebase-config.js
          sed -i 's|FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g' js/firebase-config.js
          sed -i 's|FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' js/firebase-config.js
          sed -i 's|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' js/firebase-config.js
          sed -i 's|FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g' js/firebase-config.js
          sed -i 's|FIREBASE_MEASUREMENT_ID|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g' js/firebase-config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: .